main:
  - name: Home
    url: '/#top'
    weight: 10
  - name: Research
    url: '/#research'
    weight: 20
  - name: Publications
    url: '/publication/'
    weight: 30
  - name: UD's Log
    url: '/post/'
    weight: 40
  - name: About
    url: '/experiences/'
    weight: 50
  - name: CV
    url: '/uploads/uei-dar-chen-cv.pdf'
    weight: 60
